### ISSUE TITLE
`<string>`: LibFuzzer failure during startup due to `basic_string::append` failing under ASAN

### ISSUE THREAD

**Issue by Porges** [microsoft/STL#3886]
# Describe the bug

We are seeing ASAN-originated LibFuzzer failures with the following stacktrace:

```
==6048==ERROR: AddressSanitizer: container-overflow on address 0x11d0e55a0f17 at pc 0x7ff7e1b09a3c bp 0x009688c8eeb0 sp 0x009688c8e640
WRITE of size 2 at 0x11d0e55a0f17 thread T0
    #0 0x7ff7e1b09a3b in __asan_wrap_memmove D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_common_interceptors.inc:813
    #1 0x7ff7e1c4daf5 in std::_Char_traits<char,int>::move VCCRT\crtw32\stdhpp\xstring:119
    #2 0x7ff7e1c4daf5 in std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>::append(char const *const, unsigned __int64) VCCRT\crtw32\stdhpp\xstring:3313
    #3 0x7ff7e1b542ad in std::basic_string<char,std::char_traits<char>,std::allocator<char> >::append D:\a\_work\1\s\src\vctools\crt\github\stl\inc\xstring:3279
    #4 0x7ff7e1b542ad in std::operator+ D:\a\_work\1\s\src\vctools\crt\github\stl\inc\xstring:5003
    #5 0x7ff7e1b542ad in fuzzer::DirPlusFile(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIO.cpp:133
    #6 0x7ff7e1b51dd8 in fuzzer::ListFilesInDirRecursive(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, long *, class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>> *, bool) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIOWindows.cpp:137
    #7 0x7ff7e1b548b3 in fuzzer::GetSizedFilesFromDir(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::vector<struct fuzzer::SizedFile, class std::allocator<struct fuzzer::SizedFile>> *) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIO.cpp:125
    #8 0x7ff7e1b617fa in fuzzer::ReadCorpora D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:631
    #9 0x7ff7e1b5ec81 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:911
    #10 0x7ff7e1b50ab2 in main D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #11 0x7ff7e1b3f22b in invoke_main VCCRT\vcstartup\src\startup\exe_common.inl:78
    #12 0x7ff7e1b3f22b in __scrt_common_main_seh VCCRT\vcstartup\src\startup\exe_common.inl:288
    #13 0x7ffc9c9b7613  (C:\Windows\System32\KERNEL32.DLL+0x180017613)
    #14 0x7ffc9cc226f0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526f0)
```

The ASAN failure (two different binaries here):

```
WRITE of size 2 at 0x11d0e55a0f17 thread T0
0x11d0e55a0f17 is located 103 bytes inside of 112-byte region [0x11d0e55a0eb0,0x11d0e55a0f20)
```

```
WRITE of size 2 at 0x11d013da1077 thread T0
0x11d013da1077 is located 103 bytes inside of 112-byte region [0x11d013da1010,0x11d013da1080)
```

And the allocation information is:

```
0x11d0e55a0f17 is located 103 bytes inside of 112-byte region [0x11d0e55a0eb0,0x11d0e55a0f20)
allocated by thread T0 here:
    #0 0x7ff7e1b23fae in operator new(unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_win_new_scalar_thunk.cpp:40
    #1 0x7ff7e1b53a77 in std::allocator<char>::allocate D:\a\_work\1\s\src\vctools\crt\github\stl\inc\xmemory:951
    #2 0x7ff7e1b53a77 in std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>(struct std::_String_constructor_concat_tag, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, char const *const, unsigned __int64, char const *const, unsigned __int64) D:\a\_work\1\s\src\vctools\crt\github\stl\inc\xstring:2833
    #3 0x7ff7e1b54292 in std::operator+ D:\a\_work\1\s\src\vctools\crt\github\stl\inc\xstring:4988
    #4 0x7ff7e1b54292 in fuzzer::DirPlusFile(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIO.cpp:133
    #5 0x7ff7e1b51dd8 in fuzzer::ListFilesInDirRecursive(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, long *, class std::vector<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>, class std::allocator<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>>>> *, bool) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIOWindows.cpp:137
    #6 0x7ff7e1b548b3 in fuzzer::GetSizedFilesFromDir(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char>> const &, class std::vector<struct fuzzer::SizedFile, class std::allocator<struct fuzzer::SizedFile>> *) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerIO.cpp:125
    #7 0x7ff7e1b617fa in fuzzer::ReadCorpora D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:631
    #8 0x7ff7e1b5ec81 in fuzzer::FuzzerDriver(int *, char ***, int (__cdecl *)(unsigned char const *, unsigned __int64)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerDriver.cpp:911
    #9 0x7ff7e1b50ab2 in main D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\fuzzer\FuzzerMain.cpp:20
    #10 0x7ff7e1b3f22b in invoke_main VCCRT\vcstartup\src\startup\exe_common.inl:78
    #11 0x7ff7e1b3f22b in __scrt_common_main_seh VCCRT\vcstartup\src\startup\exe_common.inl:288
    #12 0x7ffc9c9b7613  (C:\Windows\System32\KERNEL32.DLL+0x180017613)
    #13 0x7ffc9cc226f0  (C:\Windows\SYSTEM32\ntdll.dll+0x1800526f0)
```

# Command-line test case

I've not yet created a minimal repro; all the code in the stack in question is provided by VC/STL (LibFuzzer libraries). I can provide the problematic binaries internally.

**Comment by StephanTLavavej** [comment]
@strega-nil-ms Was this the issue that was caused by mixing old TUs that lacked the ASAN annotations?

**Comment by strega-nil-ms** [comment]
Yeah, it was; unless we have a further repro, I'd consider this not a bug.
