### ISSUE TITLE
Sporadic STL-ASan-CI failures mentioning `__asan_wrap_memmove`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4696]
Totally distinct from #4324.

Date       | Toolset | PR         | Arch | Test
-----------|---------|------------|------|------
2024-05-24 | 17.11p1 | #4685 (CI) | x64  | [libcxx `facet.ctype.char.members/toupper_many.pass.cpp`](https://dev.azure.com/vclibs/STL/_build/results?buildId=16890&view=results)

```
==4900==ERROR: Failed to override local function at '0x7ff7d077c3e0' with sanitizer function '__asan_wrap_memmove'
AddressSanitizer: CHECK failed: sanitizer_win_interception.cpp:143 "(("Failed to replace local function with sanitizer version." && 0)) != (0)" (0x0, 0x0) (tid=9080)
    #0 0x7ff8139b04df in __asan::CheckUnwind D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_rtl.cpp:69
    #1 0x7ff81396f593 in __sanitizer::CheckFailed(char const *, int, char const *, unsigned __int64, unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_termination.cpp:86
    #2 0x7ff81396ea15 in __sanitizer_override_function D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_win_interception.cpp:143
    #3 0x7ff7d05ba63c in __sanitizer::override_function(char const *, unsigned __int64) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_win_thunk_interception.cpp:29
    #4 0x7ff7d05ba60e in __sanitizer::initialize_thunks(int (__cdecl *const *)(void), int (__cdecl *const *)(void)) D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_win_thunk_interception.cpp:48
    #5 0x7ff7d05ba5b6 in __sanitizer_thunk_init D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\sanitizer_common\sanitizer_win_thunk_interception.cpp:82
    #6 0x7ff8529412a9  (C:\Windows\SYSTEM32\ntdll.dll+0x1800812a9)
    #7 0x7ff8528e72f6  (C:\Windows\SYSTEM32\ntdll.dll+0x1800272f6)
    #8 0x7ff8528e885c  (C:\Windows\SYSTEM32\ntdll.dll+0x18002885c)
    #9 0x7ff852996f9f  (C:\Windows\SYSTEM32\ntdll.dll+0x1800d6f9f)
    #10 0x7ff852938517  (C:\Windows\SYSTEM32\ntdll.dll+0x180078517)
    #11 0x7ff85295de6c  (C:\Windows\SYSTEM32\ntdll.dll+0x18009de6c)
    #12 0x7ff85293831d  (C:\Windows\SYSTEM32\ntdll.dll+0x18007831d)
```

**Comment by StephanTLavavej** [comment]
I haven't seen any STL-ASan-CI failures since 2025-05-28 when we were using the 17.14p7 toolset, so I think this might have been fixed circa 18.0 / MSVC Build Tools 14.50.
