### ISSUE TITLE
README.md: Build example uses out\build\x64, test example uses build

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#779]
It would be very nice if the build and test instructions used the same example directory for binaries output.

Note that the test examples use `..\` to access the repo's source tree from the `build` subdirectory; this will need to be changed if the subdirectory becomes `out\build\x64`.

**Comment by AlexGuteniev** [comment]
It still does not work for me:

```
c:\Project\STL\out\build\x64>python tests\utils\stl-lit\stl-lit.py ..\..\..\tests\std\tests\VSO_0000000_any_calling_conventions
stl-lit.py: C:/Project/STL/llvm-project/llvm\utils\lit\lit\TestingConfig.py:102: fatal: unable to parse config file 'C:/Project/STL/tests/std/lit.cfg', traceback: Traceback (most recent call last):
  File "C:/Project/STL/llvm-project/llvm\utils\lit\lit\TestingConfig.py", line 89, in load_from_path
    exec(compile(data, path, 'exec'), cfg_globals, None)
  File "C:/Project/STL/tests/std/lit.cfg", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib
```

**Comment by AlexGuteniev** [comment]
Ah, it works!
By default `python` is Python 2.7 on my system. Afraid to change %path%, so will use full path to Python 3.8
